CREATE TABLE IF NOT EXISTS ddns_record (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    updated_on DATETIME NOT NULL,
    ipv4_addr VARCHAR(15) NOT NULL,
    ipv6_addr VARCHAR(39) NOT NULL DEFAULT '::1',
    duration INTEGER DEFAULT 0
    comment TEXT NULL
);
